### ISSUE TITLE
Size Limit?

### ISSUE THREAD

**Issue by ThioJoe** [mdnahas/easy_encryption_everywhere#1]
Stumbled across this project from the par3 spec and it seems very cool. 

I was able to get the demo website to work with very small files of like a few KB. I tested various sizes files with random contents and it seems to give me an error when the file size is greater than or equal to exactly 125692 bytes. I'm not sure what the significance of that number is.

The message box says:
`An error occurred.  Check console log for details.`

and the console says

```
EasyEncryptionEverywhere.html:226 RangeError: Maximum call stack size exceeded
    at EasyEncryptionEverywhere.html:73:75
    at step (EasyEncryptionEverywhere.html:41:23)
    at Object.next (EasyEncryptionEverywhere.html:22:53)
    at fulfilled (EasyEncryptionEverywhere.html:13:58)
```

**Comment by mdnahas** [comment]
Thanks for trying it out!  And thanks for letting me know about the error! 

I didn't have that problem with Firefox on Linux. 
I was able to reproduce your error on Chromium.  (A variant of Chrome.)

It looks like another programmer has run into this problem with Chrome at a similar stack size:
https://stackoverflow.com/questions/18308700/chrome-how-to-solve-maximum-call-stack-size-exceeded-errors-on-math-max-apply

It has to do with large arrays.   (I read the entire file into an array to encrypt/encode it.)   I'll see what I can do to fix it.

**Comment by mdnahas** [comment]
This bug is fixed.  I pushed the code to Github and the new webpage to my website. 

It may take some time to propagate and you may need to purge your browser cache to get the new file.
